### ISSUE TITLE
building from source failed: Phantomjs permission denied error

### ISSUE THREAD

**Issue by ThomasRoehl** [assistify/Rocket.Chat#102]
### Description:

I get a permission denied error from Phantomjs when running `meteor npm install` in a docker-container.
The issue is known from the original Rocket.Chat repo and is related to the version 2.1.13 of Phantomjs.

#https://github.com/RocketChat/Rocket.Chat/issues/7173

#https://github.com/RocketChat/Rocket.Chat/pull/7728

```
While loading emojione:emojione@2.2.6...:
   error: Command failed:
   /rocketchat/.meteor/packages/meteor-tool/.1.5.1.cmh41h++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm
   rebuild --update-binary
   Phantom installation failed { [Error: EACCES: permission denied, open
   '/tmp/mt-y2kql7/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/location.js']
   errno: -13,
   code: 'EACCES',
   syscall: 'open',
   path:
   '/tmp/mt-y2kql7/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/location.js'
   } Error: EACCES: permission denied, open
   '/tmp/mt-y2kql7/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/location.js'
   at Error (native)
   at Object.fs.openSync (fs.js:549:18)
   at Object.fs.writeFileSync (fs.js:1156:15)
   at writeLocationFile
   (/tmp/mt-y2kql7/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/install.js:108:6)
   at Promise._successFn
   (/tmp/mt-y2kql7/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/install.js:80:5)
   at nextTickCallback
   (/tmp/mt-y2kql7/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/node_modules/kew/kew.js:47:28)
   at nextTickCallbackWith0Args (node.js:489:9)
   at process._tickCallback (node.js:418:13)
   npm ERR! code ELIFECYCLE
   npm ERR! errno 1
   npm ERR! phantomjs@1.9.20 install: `node install.js`
   npm ERR! Exit status 1
   npm ERR!
   npm ERR! Failed at the phantomjs@1.9.20 install script.
   npm ERR! This is probably not a problem with npm. There is likely additional
   logging output above.

   npm ERR! A complete log of this run can be found in:
   npm ERR!
   /rocketchat/.meteor/packages/meteor-tool/.1.5.2_2.fkst7p++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/.npm/_logs/2017-10-20T13_03_19_753Z-debug.log
   Phantom installation failed { [Error: EACCES: permission denied, open
   '/tmp/mt-y2kql7/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/location.js']
   errno: -13,
   code: 'EACCES',
   syscall: 'open',
   path:
   '/tmp/mt-y2kql7/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/location.js'
   } Error: EACCES: permission denied, open
   '/tmp/mt-y2kql7/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/location.js'
   at Error (native)
   at Object.fs.openSync (fs.js:549:18)
   at Object.fs.writeFileSync (fs.js:1156:15)
   at writeLocationFile
   (/tmp/mt-y2kql7/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/install.js:108:6)
   at Promise._successFn
   (/tmp/mt-y2kql7/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/install.js:80:5)
   at nextTickCallback
   (/tmp/mt-y2kql7/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/node_modules/kew/kew.js:47:28)
   at nextTickCallbackWith0Args (node.js:489:9)
   at process._tickCallback (node.js:418:13)
   npm ERR! code ELIFECYCLE
   npm ERR! errno 1
   npm ERR! phantomjs@1.9.20 install: `node install.js`
   npm ERR! Exit status 1
   npm ERR!
   npm ERR! Failed at the phantomjs@1.9.20 install script.
   npm ERR! This is probably not a problem with npm. There is likely additional
   logging output above.

   npm ERR! A complete log of this run can be found in:
   npm ERR!
   /rocketchat/.meteor/packages/meteor-tool/.1.5.2_2.fkst7p++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/.npm/_logs/2017-10-20T13_03_19_753Z-debug.log


=> Your application has errors. Waiting for file change.
```

**Comment by mrsimpson** [comment]
Rocket chat itself is running in a container und performing automated tests there. So obviously, there is a solution ;-)
Have you checked RocketChat‘s Travis.yml?

**Comment by ThomasRoehl** [comment]
I just noticed, I got the same error in travis. But when travis attempted a second try for the command, it ran through.
