### ISSUE TITLE
Internal server error when creating a new request

### ISSUE THREAD

**Issue by ruKurz** [assistify/Rocket.Chat#180]
After releasing `v0.59.3-0.5.1`, there comes up an internal error when creating a new request.

```
[34mI20171221-12:53:04.930(1) Exception while invoking method 'createRequest' TypeError: Cannot read property 'desktopNotifications' of undefined
   at /opt/Rocket.Chat/programs/server/packages/assistify_help-request.js:993:108
   at Array.forEach (native)
   at createNotifications (/opt/Rocket.Chat/programs/server/packages/assistify_help-request.js:983:14)
   at [object Object].Meteor.methods.createRequest (/opt/Rocket.Chat/programs/server/packages/assistify_help-request.js:1035:3)
   at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
   at [object Object].methodsMap.(anonymous function) (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:2480:26)
   at maybeAuditArgumentChecks (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:1857:12)
   at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:903:20
   at [object Object].EVp.withValue (packages/meteor.js:1134:15)
   at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:902:47
   at [object Object].EVp.withValue (packages/meteor.js:1134:15)
   at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:901:46
   at [object Object]._.extend.protocol_handlers.method (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:874:21)
   at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:753:85
```

**Comment by mrsimpson** [comment]
@vickyokrm can help here, I suppose
