### ISSUE TITLE
When creating questions on specific topics, a server error 500 occurs.

### ISSUE THREAD

**Issue by ruKurz** [assistify/Rocket.Chat#288]

**Comment by mrsimpson** [comment]
Exception while invoking method 'createRequest'
```
WriteError({"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: team.rocketchat_subscription index: rid_1_u._id_1 dup key: { : \"FgxucLjnpE7N2q8yG\", : \"txyvsGim65Rab3z8y\" }","op":{"open":true,"alert":false,"unread":0,"userMentions":0,"groupMentions":0,"ts":"2017-11-15T09:34:19.628Z","rid":"FgxucLjnpE7N2q8yG","name":"investors-relations-315","fname":"Investors-Relations-315","t":"r","u":{"_id":"txyvsGim65Rab3z8y","username":"Jan"},"_updatedAt":"2017-11-15T09:34:19.643Z","_id":"3NyjrZfPZxormtDvN"}})
  at Object.Future.wait (/opt/Rocket.Chat/programs/server/node_modules/fibers/future.js:449:15)
  at [object Object].<anonymous> (packages/meteor.js:209:22)
  at [object Object].MongoConnection.(anonymous function) [as insert] (/opt/Rocket.Chat/programs/server/packages/mongo.js:790:49)
  at Object.<anonymous> (packages/matb33_collection-hooks.js:395:18)
  at Object.collection.(anonymous function) [as insert] (packages/matb33_collection-hooks.js:146:21)
  at [object Object].insert (/opt/Rocket.Chat/programs/server/packages/mongo.js:3767:38)
  at ModelsBaseDb.insert (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:12944:54)
  at ModelSubscriptions.insert (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:6511:36)
  at ModelSubscriptions.createWithRoomAndUser (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:10169:16)
  at EventEmitter.RocketChat.createRoom (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:4681:35)
  at [object Object].Meteor.methods.createRequest (/opt/Rocket.Chat/programs/server/packages/assistify_help-request.js:1013:37)
  at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
  at [object Object].methodsMap.(anonymous function) (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:2480:26)
  at maybeAuditArgumentChecks (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:1857:12)
  at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:903:20
  at [object Object].EVp.withValue (packages/meteor.js:1134:15)
  at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:902:47
  at [object Object].EVp.withValue (packages/meteor.js:1134:15)
  at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:901:46
  at [object Object]._.extend.protocol_handlers.method (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:874:21)
  at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:753:85

    - - - - -
  at Function.MongoError.create (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)
  at toError (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:139:22)
  at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:669:23
  at handleCallback (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:120:56)
  at resultHandler (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/bulk/ordered.js:421:14)
  at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:469:18
  at nextTickCallbackWith0Args (node.js:420:9)
  at process._tickDomainCallback (node.js:390:13)

**Comment by mrsimpson** [comment]
There is some inconsistency in our Database. It *might* have something to do with renaming of user names, see https://github.com/RocketChat/Rocket.Chat/issues/6535 .
There has been a fix that this issue doesn't occur anymore, but data needs to be migrated.
Might want to check on https://github.com/RocketChat/Rocket.Chat/pull/9432#issuecomment-377346532
