### ISSUE TITLE
Push-Notifications do not work

### ISSUE THREAD

**Issue by ruKurz** [assistify/Rocket.Chat#469]
### Description:

No push notifications are sent

### Steps to reproduce:

1. Goto your user's profile
2. Log-out from all other devices (make sure you're not logged into your mobile)
3. Log-out from the chat itself
4. Use another user and send a message by mentioning the logged out user

### Expected behavior:

getting a push notification

### Actual behavior:

No notification is sent

### Server Setup Information:
```
+----------------------------------------------------------------+ 
|                                                                | 
|  Rocket.Chat Version: 0.68.5                                   | 
|       NodeJS Version: 8.11.3 - x64                             | 
|             Platform: linux                                    | 
|         Process Port: 3000                                     | 
|             Site URL: https://team.assistify-test.noncd.db.de  | 
|     ReplicaSet OpLog: Enabled                                  | 
|          Commit Hash: 7b9eb7b530                               | 
|        Commit Branch: develop                                  | 
|                                                                | 
+----------------------------------------------------------------+ 
```

### Additional context

Tested with Andriod `6.0`

### Relevant logs:

```
[34mI20180910-06:01:50.283(0) rocketchat_logger rocketchat_logger.js:278 [31mSystem ➔ error Error sending push to gateway (0 try) -> { Error: getaddrinfo ENOTFOUND gateway.rocket.chat gateway.rocket.chat:443     at errnoException (dns.js:50:10)     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)    code: 'ENOTFOUND',   errno: 'ENOTFOUND',   syscall: 'getaddrinfo',   hostname: 'gateway.rocket.chat',   host: 'gateway.rocket.chat',   port: 443 } 
```

**Comment by ruKurz** [comment]
This issue seems to be related with the environment and is not a general RC issue.
Sending a Push-Notification via the RC Admin UI does work on the test environment, but not on the cluster environment.
