### ISSUE TITLE
Profile picture upload does not work 

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#475]
Uploading profile pictures does not work. Uploading regular attachments works.

**Comment by jschirrmacher** [comment]
See #435

**Comment by ruKurz** [comment]
There occurs a exception when uploading a avatar.

```
Exception in callback of async function: Error: Expected positive integer for width but received 600 of type string
    at Object.invalidParameterError (/app/bundle/programs/server/npm/node_modules/sharp/lib/is.js:101:10)
    at Sharp.resize (/app/bundle/programs/server/npm/node_modules/sharp/lib/resize.js:82:16)
    at s.metadata.Meteor.bindEnvironment (/app/bundle/programs/server/packages/rocketchat_file-upload.js:389:160)
    at runWithEnvironment (packages/meteor.js:1238:24)

{ Error: ENOENT: no such file or directory, stat '/tmp/zipFiles/txyvsGim65Rab3z8y.zip'


  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/tmp/zipFiles/txyvsGim65Rab3z8y.zip' }
```

**Comment by ruKurz** [comment]
This issue is caused by automated configuration of the setting `Accounts_AvatarSize` which sets the value as String. By changing the value via Admin UI the problem disappears.

**Comment by jschirrmacher** [comment]
Partly. At least file upload works now. Using a URL still doesn't.

**Comment by ruKurz** [comment]
Duplicates #435
