### ISSUE TITLE
Knowledge base does not work in livechat

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#496]
The knowledge base does not show anything in livechat, even no error messages:

![livechat-knowledgebase](https://user-images.githubusercontent.com/3596824/45361677-277c8900-b5d3-11e8-9563-1bb10d94b0c9.png)

**Comment by ThomasRoehl** [comment]
I can see the following error:
![image](https://user-images.githubusercontent.com/11913979/45366886-3a498a80-b5e0-11e8-99d7-efb852518245.png)

**Comment by ThomasRoehl** [comment]
![image](https://user-images.githubusercontent.com/11913979/45367293-34a07480-b5e1-11e8-81cd-ecc3199f3002.png)
Found This room which shows the widget and some results

**Comment by ruKurz** [comment]
There occurs an exception:
```
Exception in defer callback: TypeError: Cannot read property 'roles' of undefined
    at isMessageRelevant (/app/bundle/programs/server/packages/assistify_ai.js:896:12)
    at /app/bundle/programs/server/packages/assistify_ai.js:914:7
    at /app/bundle/programs/server/packages/rocketchat_lib.js:1280:28
    at Array.reduce (<anonymous>:null:null)
    at Object.RocketChat.callbacks.run (/app/bundle/programs/server/packages/rocketchat_lib.js:1269:28)
    at Meteor.defer (/app/bundle/programs/server/packages/rocketchat_lib.js:5784:35)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
    at packages/meteor.js:502:25
    at runWithEnvironment (packages/meteor.js:1238:24)
```

**Comment by ruKurz** [comment]
We fixed the `'roles' of undefined` issue.
But the knowledge base still not working.
The current behavior seems not to be related with the live-chat.
Instead it occurs in several different channels.
